// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimbirSquize.Data.Testing;

namespace SimbirSquize.Migrations.Testing
{
    [DbContext(typeof(TestingContext))]
    [Migration("20210911095350_AddBaseEntityInterfaceWithCreatedAtUpdatedAtAndDeletedAt")]
    partial class AddBaseEntityInterfaceWithCreatedAtUpdatedAtAndDeletedAt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");
#pragma warning restore 612, 618
        }
    }
}
